# setup webservers
---
  - hosts: webservers
    become: true # excute commands as root
    tasks:
      - name: install apache webserver
        yum: name=apache2 state=present

      - name: delete original index.html file
        file: path=/var/www/html/index.html state=absent