# setup webservers
---
  - hosts: webservers
    become: true # excute commands as root
    tasks:
      - name: create new index.html file
        lineinfile:
          create: yes
          path: /var/www/html/index.html
          line: <html>Hello from server1</html>
        notify: start apache

    handlers:
      - name: start apache
        service: name=apache2 state=started